### ISSUE TITLE
[Req] Support for Powershell

### ISSUE THREAD

**Issue by Geobert** [micouy/kn#6]
I don't know if it's possible, but can we use `kn` with Powershell (Windows and Linux)

**Comment by micouy** [comment]
It's definitely possible (since `zoxide` works on PS) but I have never wrote a script for Powershell (or used it, for that matter). You can create a PR to speed this up. It will probably be only ~40 loc.

Take a look at scripts in [zoxide/templates](https://github.com/ajeetdsouza/zoxide/tree/main/templates). There's one for Powershell. I reused their code in my scripts [init/](https://github.com/micouy/kn/tree/master/init).

**Comment by micouy** [comment]
I've implemented it but I won't merge it for now. You can get it from branch [feat/powershell-support](https://github.com/micouy/kn/tree/feat/powershell-support).

I'm not sure about the correctness of the script ([here](https://github.com/micouy/kn/blob/feat/powershell-support/init/kn.powershell.template)) and the invocation that is supposed to go to your PS profile ([here](https://github.com/micouy/kn/tree/feat/powershell-support#configuring-your-shell)). Let me know if you're able to review it.
